PoissonDistribution <- function(lambda) {
  results <- list()
  
  results$description <-
    'TODO Raluca/Robert write here some text about this distribution from Wikipedia.'
  
  results$type <- 'discrete'
  
  # trick for max value of a Poisson distribution
  # the value of max is needed only for exercise 10
  # exercise 10 requires summation when evaluation the expected value of g(X)
  # the supported domain for Poisson distribution is N (which is an infinite set) and we can't do summation on N
  # thus we take the max value as the last integer (with an associated probability>0) than can be generated by R
  # in order to make sure that we really considered all possible values (with an associated probability>0) we raise the results to the power of 2
  results$support <-
    c(
      min = 0,
      max = qpois(1 - .Machine$double.eps ** 0.25, lambda) ** 2 %>% as.integer()
    )
  
  results$mean <- lambda
  
  results$variance <- lambda
  
  results$median <- as.integer(lambda + 1 / 3 - 0.02 / lambda)
  
  if (lambda == as.integer(lambda)) {
    results$mode <-
      paste0(lambda - 1, ' and ', lambda)
  } else{
    results$mode <- as.integer(lambda)
  }
  
  results$skewness <- lambda ** (-1 / 2)
  
  results$excess_kurtosis <- lambda ** (-1)
  
  min.x <- 0
  max.x <- qpois(0.999, lambda)
  x <- min.x:max.x
  
  pmf <- dpois(x, lambda)
  results$plot_pmf <-
    PlotPdfOrPmf(x, pmf, 'Poisson distribution', FALSE)
  
  cdf <- ppois(x, lambda)
  results$plot_cdf <-
    PlotCdf(x, cdf, 'Poisson distribution', FALSE)
  
  results$pmf <- function(x) {
    # if x is not an natural number then dpois(x,lambda) return 0 as expected, but with an warning
    # suppressWarnings removes the warning while keeping the returned value
    dpois(x, lambda) %>%
      suppressWarnings() %>%
      return()
  }
  
  return(results)
}
